# Input and Output

In [ ]:
#02-03-2023                                                             21b01a1288

In [42]:
from __future__ import print_function
import numpy as np

In [43]:
np.__version__

'1.21.5'

In [44]:
from datetime import date
print(date.today())

2023-02-03


## NumPy binary files (NPY, NPZ)

Q1. Save x into `temp.npy` and load it.

In [45]:
x = np.arange(10)
np.save('temp.npy', x)

# Check if there exists the 'temp.npy' file.
import os
if os.path.exists('temp.npy'):
    x2 = np.load('temp.npy')
    print(np.array_equal(x, x2))


True


Q2. Save x and y into a single file 'temp.npz' and load it.

In [46]:
x = np.arange(10)
y = np.arange(11, 20)
np.savez('temp.npz', x=x, y=y)
with np.load('temp.npz')  as data:
    x2 = data['x']
    y2 = data['y']
    print(np.array_equal(x, x2))
    print(np.array_equal(y, y2))


True
True


## Text files

Q3. Save x to 'temp.txt' in string format and load it.

In [47]:
x = np.arange(10).reshape(2, 5)
header = 'num1 num2 num3 num4 num5'
np.savetxt('temp.txt', x, fmt="%d", header=header) 
np.loadtxt('temp.txt')

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

Q4. Save `x`, `y`, and `z` to 'temp.txt' in string format line by line, then load it.

In [48]:
x = np.arange(10)
y = np.arange(11, 21)
z = np.arange(22, 32)
print(np.savetxt('temp.txt', (x, y, z), fmt='%d'))
print(np.loadtxt('temp.txt'))

None
[[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]
 [11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
 [22. 23. 24. 25. 26. 27. 28. 29. 30. 31.]]


Q5. Convert `x` into bytes, and load it as array.

In [49]:
x = np.array([1, 2, 3, 4])
x_bytes = x.tobytes()
x2 = np.frombuffer(x_bytes,dtype=x.dtype)
print(np.array_equal(x, x2))


True


Q6. Convert `a` into an ndarray and then convert it into a list again.

In [50]:
a = [[1, 2], [3, 4]]
x = np.array(a)
a2 = x.tolist()
print(a == a2)

True


## String formatting¶

Q7. Convert `x` to a string, and revert it.

In [51]:
x = np.arange(10).reshape(2,5)
x_str =  np.array_str(x)
print(x_str, "\n", type(x_str))
x_str = x_str.replace("[", "") # [] must be stripped
x_str = x_str.replace("]", "")
x2 = np.fromstring(x_str, dtype=x.dtype, sep=" ").reshape(x.shape)
assert np.array_equal(x, x2)



[[0 1 2 3 4]
 [5 6 7 8 9]] 
 <class 'str'>


## Text formatting options

Q8. Print `x` such that all elements are displayed with precision=1, no suppress.

In [52]:
x = np.random.uniform(size=[10,100])
np.set_printoptions(precision=1, suppress=True)
print(x)

[[0.9 0.4 0.1 0.1 0.2 1.  0.9 0.1 0.5 0.  0.5 0.1 0.4 0.8 0.2 0.1 0.6 0.1
  0.7 0.7 0.6 0.8 0.7 0.4 0.4 0.1 0.  0.7 0.2 0.1 0.3 0.3 0.7 0.6 0.8 1.
  0.2 0.8 0.9 1.  0.7 0.5 1.  1.  0.3 0.2 0.4 1.  0.5 0.8 0.8 0.3 0.9 0.3
  0.7 0.9 0.2 0.8 0.1 0.8 0.7 0.1 1.  0.4 0.  0.7 0.6 0.8 0.3 0.2 0.7 0.1
  0.8 0.7 0.3 0.8 0.8 0.5 1.  0.8 0.8 0.7 0.4 0.8 0.6 1.  0.8 1.  0.  0.3
  1.  0.5 0.8 0.1 0.2 1.  0.7 0.8 0.2 0.7]
 [0.4 0.8 0.7 0.6 0.  0.5 0.4 0.2 0.7 0.3 1.  0.6 0.1 1.  0.2 0.7 0.2 0.
  0.8 0.8 0.3 0.8 0.8 0.7 0.2 0.9 0.7 0.4 0.3 1.  0.6 0.5 0.7 0.9 0.4 0.1
  0.5 0.8 0.5 0.4 1.  0.1 0.2 0.2 0.1 0.8 0.1 0.8 0.8 0.2 0.3 0.9 0.5 0.8
  0.4 0.4 0.  0.5 0.8 0.  0.3 0.7 0.  0.2 0.6 0.  0.5 0.3 0.3 0.4 0.3 0.2
  0.2 0.8 0.6 0.9 0.1 0.  0.6 0.2 0.5 0.6 0.1 0.7 0.5 0.6 0.1 0.4 0.3 0.4
  0.7 0.6 0.2 0.3 0.8 0.2 0.5 0.1 0.2 0.3]
 [0.4 0.1 1.  0.8 0.9 0.4 1.  0.6 0.6 0.3 0.4 0.3 0.9 0.9 0.4 0.6 0.6 0.9
  0.7 0.1 0.2 0.  0.8 0.  0.2 0.5 0.9 0.3 0.7 0.9 0.1 0.4 0.8 1.  0.6 0.6
  0.6 0.  0.7 0.  0.9 0.5 0.

## Base-n representations

Q9. Convert 12 into a binary number in string format.

In [53]:
out1 = np.binary_repr(12)
out2 = np.base_repr(12, base=2)
assert out1 == out2
print(out1)

1100


Q10. Convert 12 into a hexadecimal number in string format.

In [54]:
np.base_repr(1100, base=16)

'44C'